name: birb_check_flutter
description: A project that allows you to talk about and share your birbs.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
